{
  "release": "{{ .ani.kubeflow.release }}",
  "kubeconfig": "{{ .ani.run.kubeconfig }}",
  "logs_dir": "{{ .ani.run.logs_dir }}",
  "connections_dir": "{{ .ani.run.connections_dir }}",
  "artifact_root": "{{ .ani.artifact_root }}",
  "registry": "{{ .ani.registry }}",
  "images": {{ toJson .ani.kubeflow.images }},
  "owner": {{ toJson .kubernetes.cluster_name }},
  "network_stack": {{ toJson .ani.kubeflow.network_stack }},
  "network_policy": {{ toJson .ani.kubeflow.network_policy }},
  "network_policy_contract": {{ toJson .ani.kubeflow.network_policy_contract }},
  "network_image": {{ toJson .ani.kubeflow.network_image }},
  "node_addresses": {{ toJson .ani.node_addresses }},
  "entry_address": "{{ .ani.kubeflow.entry_address }}",
  "http_port": {{ .ani.kubeflow.http_port }},
  "grpc_port": {{ .ani.kubeflow.grpc_port }},
  "database_class": "{{ .ani.kubeflow.database_class }}",
  "database_size": "{{ .ani.kubeflow.database_size }}",
  "workspace_class": "{{ .ani.kubeflow.workspace_class }}",
  "workspace_max_size": "{{ .ani.kubeflow.workspace_max_size }}",
  "workspace_max_claims": {{ .ani.kubeflow.workspace_max_claims }},
  "workspace_quota_size": "{{ .ani.kubeflow.workspace_quota_size }}",
  "workspace_mode": "{{ .ani.kubeflow.workspace_mode }}",
  "tenants": {{ toJson .ani.kubeflow.tenants }}
}
