apiVersion: v1
kind: Service
metadata:
  name: ani-smoke-backend
  namespace: ani-installer-smoke
spec:
  selector:
    app: ani-smoke-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000